openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://task-api-6k05.onrender.com
    description: Production server on render
tags:
  - name: Tasks
    description: Task related endpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
  /tasks/{id}:
    get:
      summary: Get a Task by id
      tags:
        - Tasks
      parameters:
        - name: id
          in: query
          required: true
          description: Unique Task identifier
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./components/schemas/Task.yaml
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: ./components/responses/BadRequest.yaml
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                $ref: ./components/responses/NotFoundError.yaml
